### ISSUE TITLE
Option to import using symlinks

### ISSUE THREAD

**Issue by mortenlj** [mumoshu/kubeconf#4]
I have one kubeconfig that is tracked in git.

When importing this into config-registry, a hardlink is created to the original file.

When doing various git commands, the original file is replaced, leaving the hardlink in the config registry to point to the original contents, and not the updated contents from git.

It would be useful if you could tell config-registry to import using a symlink instead, which would continue to point to the same filename regardless of the operations git performs.

**Comment by mumoshu** [comment]
> When doing various git commands, the original file is replaced, leaving the hardlink in the config registry to point to the original contents, and not the updated contents from git.

@mortenlj Hey! This is expected behavior that originates from the early design discussion for this project. You can see it at https://github.com/kubernetes-sigs/krew-index/pull/857#issuecomment-711071201.

In short, `config-registry` isn't a registry of links. It's a registry of configs and that's why it doesn't rely on symlinks.

**Comment by mortenlj** [comment]
Ah. In that case I guess I'll have to find some other solution for managing my configs :disappointed:

**Comment by mumoshu** [comment]
@mortenlj Yep. What you meant looks more like a config registry backed by a specific git repository. Maybe you can fork this repository and replace the config storage part with a read-through cache of a remote git repo if you're going to build one yourself! Cheers.
